config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :location, optional: true

  validates_presence_of :name, :quantity, :date, :description
  validates_numericality_of :quantity
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :items, dependent: :nullify

  validates_presence_of :city, :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :quantity, :date, :description, :location_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
    @item = Item.where(location: @location)
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:city, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.select :location_id, options_from_collection_for_select(Location.all, :id, :city, item.location_id), :include_blank => true %>
  </div>

  <div mt-2 pt-2>
    <%= form.submit "Submit", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= item.date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= item.location.present? ? item.location.city : "Not assigned to a Location" %>
  </p>

</div>

app/views/items/_items_table.html.erb
<div id="items">
  <table class="table table-striped">
    <thead>
      <tr>
        <td>
          Name
        </td>
        <td>
          Location
        </td>
        <td>
          Quantity
        </td>
        <td>
          Date
        </td>
        <td>
          Show
        </td>
        <td>
          Edit
        </td>
        <td>
          Delete
        </td>
      </tr>
    </thead>
    <% items.each do |item| %>
      <tbody>
        <tr>
          <td>
            <%= item.name %>
          </td>
          <td>
            <%= item.location_id.present? ? Location.find(item.location_id).city : "Not assigned to a Location" %>
          </td>
          <td>
            <%= item.quantity %>
          </td>
          <td>
            <%= item.date %>
          </td>
          <td>
            <%= link_to "Show", item, class:"btn btn-light"%>
          </td>
          <td>
            <%= link_to "Edit", edit_item_path(item), class:"btn btn-light"%>
          </td>
          <td>
            <%= button_to "Delete", item, method: :delete, class:"btn btn-danger"%>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item, class: "btn btn-primary"  %>
  <%= link_to "Back to items", items_path, class: "btn btn-primary" %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>
<%= link_to "New item", new_item_path, class: "btn btn-primary" %>
<%= link_to "Locations", locations_path, class: "btn btn-primary p-1" %>

<%= render 'items_table', items: @items %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path, class: "btn btn-primary" %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-primary p-1"  %>
  <%= link_to "Back to items", items_path,class: "btn btn-primary p-1"  %>

  <%= button_to "Destroy this item", @item, method: :delete,class: "btn btn-danger p-1"  %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand h1" href="<%= root_path %>">Inventrory</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div mt-2 pt-2>
    <%= form.submit "Submit", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>City:</strong>
    <%= location.city %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= location.address %>
  </p>

</div>

app/views/locations/_locations_table.html.erb
<div id="locations">
  <table class="table table-striped">
    <thead>
      <tr>
        <td>
          City
        </td>
        <td>
          Address
        </td>
        <td>
          Show
        </td>
        <td>
          Edit
        </td>
        <td>
          Delete
        </td>
      </tr>
    </thead>
    <% locations.each do |location| %>
      <tbody>
        <tr>
          <td>
            <%= location.city %>
          </td>
          <td>
            <%= location.address %>
          </td>
          <td>
            <%= link_to "Show", location, class:"btn btn-light"%>
          </td>
          <td>
            <%= link_to "Edit", edit_location_path(location), class:"btn btn-light"%>
          </td>
          <td>
            <%= button_to "Delete", location, method: :delete, class:"btn btn-danger"%>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location, class: "btn btn-primary" %>
  <%= link_to "Back to locations", locations_path, class: "btn btn-primary" %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<%= link_to "New location", new_location_path, class: "btn btn-primary" %>
<%= link_to "Items", items_path, class: "btn btn-primary p-1" %>

<%= render 'locations_table', locations: @locations %>


<%= link_to "Back to Homepage", root_path, class: "btn btn-primary p-1" %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path, class: "btn btn-primary" %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<h2>All items on this Location</h2>
<% if !@item.empty? %>
  <%= render 'items/items_table', items: @item %>
<% else %>
  <p>No items assigned to this Location</p>
<% end %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location), class: "btn btn-primary p-1" %>
  <%= link_to "Back to locations", locations_path, class: "btn btn-primary p-1" %>

  <%= button_to "Destroy this location", @location, method: :delete, class: "btn btn-danger p-1" %>
</div>